import { adminGuard } from './guards/admin.guard';
import { authGuard } from './guards/auth.guard';
import { storeGuard } from './guards/store.guard';
import { ShellLayoutComponent } from './layouts/shell-layout.component';
export const routes = [
    {
        path: '',
        component: ShellLayoutComponent,
        children: [
            { path: '', loadComponent: () => import('./pages/home/home.component').then((m) => m.HomePageComponent) },
            { path: 'landing', loadComponent: () => import('./pages/landing/landing.component').then((m) => m.LandingPageComponent) },
            { path: 'login', loadComponent: () => import('./pages/login/login.component').then((m) => m.LoginPageComponent) },
            { path: 'cadastro', loadComponent: () => import('./pages/register/register.component').then((m) => m.RegisterPageComponent) },
            { path: 'recuperar-senha', loadComponent: () => import('./pages/forgot-password/forgot-password.component').then((m) => m.ForgotPasswordPageComponent) },
            { path: 'perfil', canActivate: [authGuard], loadComponent: () => import('./pages/profile/profile.component').then((m) => m.ProfilePageComponent) },
            { path: 'alterar-senha', canActivate: [authGuard], loadComponent: () => import('./pages/change-password/change-password.component').then((m) => m.ChangePasswordPageComponent) },
            { path: 'enderecos', canActivate: [authGuard], loadComponent: () => import('./pages/addresses/addresses.component').then((m) => m.AddressesPageComponent) },
            { path: 'restaurantes', loadComponent: () => import('./pages/restaurants/restaurants.component').then((m) => m.RestaurantsPageComponent) },
            { path: 'mercados', loadComponent: () => import('./pages/markets/markets.component').then((m) => m.MarketsPageComponent) },
            { path: 'mercado', redirectTo: 'mercados', pathMatch: 'full' },
            { path: 'farmacias', loadComponent: () => import('./pages/pharmacies/pharmacies.component').then((m) => m.PharmaciesPageComponent) },
            { path: 'farmacia', redirectTo: 'farmacias', pathMatch: 'full' },
            { path: 'padarias', loadComponent: () => import('./pages/bakeries/bakeries.component').then((m) => m.BakeriesPageComponent) },
            { path: 'lanchonetes', loadComponent: () => import('./pages/snack-bars/snack-bars.component').then((m) => m.SnackBarsPageComponent) },
            { path: 'acougues', loadComponent: () => import('./pages/butchers/butchers.component').then((m) => m.ButchersPageComponent) },
            { path: 'pet-shops', loadComponent: () => import('./pages/pet-shops/pet-shops.component').then((m) => m.PetShopsPageComponent) },
            { path: 'busca', loadComponent: () => import('./pages/search/search.component').then((m) => m.SearchPageComponent) },
            { path: 'produto/:id', loadComponent: () => import('./pages/product/product.component').then((m) => m.ProductPageComponent) },
            { path: 'carrinho', loadComponent: () => import('./pages/cart/cart.component').then((m) => m.CartPageComponent) },
            { path: 'checkout', canActivate: [authGuard], loadComponent: () => import('./pages/checkout/checkout.component').then((m) => m.CheckoutPageComponent) },
            { path: 'meus-pedidos', canActivate: [authGuard], loadComponent: () => import('./pages/my-orders/my-orders.component').then((m) => m.MyOrdersPageComponent) },
            { path: 'pedidos', redirectTo: 'meus-pedidos', pathMatch: 'full' },
            { path: 'favoritos', canActivate: [authGuard], loadComponent: () => import('./pages/favorites/favorites.component').then((m) => m.FavoritesPageComponent) },
            { path: 'cupons', canActivate: [authGuard], loadComponent: () => import('./pages/coupons/coupons.component').then((m) => m.CouponsPageComponent) },
            { path: 'carteira', canActivate: [authGuard], loadComponent: () => import('./pages/wallet/wallet.component').then((m) => m.WalletPageComponent) },
            { path: 'avaliacoes', canActivate: [authGuard], loadComponent: () => import('./pages/reviews/reviews.component').then((m) => m.ReviewsPageComponent) },
            { path: 'notificacoes', canActivate: [authGuard], loadComponent: () => import('./pages/notifications/notifications.component').then((m) => m.NotificationsPageComponent) },
            { path: 'pagamentos', canActivate: [authGuard], loadComponent: () => import('./pages/payments/payments.component').then((m) => m.PaymentsPageComponent) },
            { path: 'pagamentos/pix', canActivate: [authGuard], loadComponent: () => import('./pages/payment-pix/payment-pix.component').then((m) => m.PaymentPixPageComponent) },
            { path: 'pagamentos/cartao', canActivate: [authGuard], loadComponent: () => import('./pages/payment-card/payment-card.component').then((m) => m.PaymentCardPageComponent) },
            { path: 'pagamentos/dinheiro', canActivate: [authGuard], loadComponent: () => import('./pages/payment-cash/payment-cash.component').then((m) => m.PaymentCashPageComponent) },
            { path: 'rastreamento', canActivate: [authGuard], loadComponent: () => import('./pages/tracking/tracking.component').then((m) => m.TrackingPageComponent) },
            { path: 'cliente', canActivate: [authGuard], loadComponent: () => import('./pages/customer-area/customer-area.component').then((m) => m.CustomerAreaPageComponent) },
            { path: 'loja', canActivate: [storeGuard], loadComponent: () => import('./pages/store-area/store-area.component').then((m) => m.StoreAreaPageComponent) },
            { path: 'area-loja', redirectTo: 'loja', pathMatch: 'full' },
            { path: 'entregador', canActivate: [authGuard], loadComponent: () => import('./pages/courier-area/courier-area.component').then((m) => m.CourierAreaPageComponent) },
            { path: 'admin', redirectTo: 'admin/dashboard', pathMatch: 'full' },
            { path: 'admin/dashboard', canActivate: [adminGuard], loadComponent: () => import('./pages/admin-dashboard/admin-dashboard.component').then((m) => m.AdminDashboardPageComponent) },
            { path: 'admin/lojas', canActivate: [adminGuard], loadComponent: () => import('./pages/admin-stores/admin-stores.component').then((m) => m.AdminStoresPageComponent) },
            { path: 'admin/categorias', canActivate: [adminGuard], loadComponent: () => import('./pages/admin-categories/admin-categories.component').then((m) => m.AdminCategoriesPageComponent) },
            { path: 'admin/banners', canActivate: [adminGuard], loadComponent: () => import('./pages/admin-banners/admin-banners.component').then((m) => m.AdminBannersPageComponent) },
            { path: 'admin/cidades', canActivate: [adminGuard], loadComponent: () => import('./pages/admin-cities/admin-cities.component').then((m) => m.AdminCitiesPageComponent) },
            { path: 'admin/cupons', canActivate: [adminGuard], loadComponent: () => import('./pages/admin-coupons/admin-coupons.component').then((m) => m.AdminCouponsPageComponent) },
            { path: 'admin/taxas', canActivate: [adminGuard], loadComponent: () => import('./pages/admin-fees/admin-fees.component').then((m) => m.AdminFeesPageComponent) },
            { path: 'admin/administradores', canActivate: [adminGuard], loadComponent: () => import('./pages/admin-admins/admin-admins.component').then((m) => m.AdminAdminsPageComponent) },
            { path: 'admin/aprovacoes/estabelecimentos', canActivate: [adminGuard], loadComponent: () => import('./pages/admin-store-approvals/admin-store-approvals.component').then((m) => m.AdminStoreApprovalsPageComponent) },
            { path: 'admin/aprovacoes/entregadores', canActivate: [adminGuard], loadComponent: () => import('./pages/admin-courier-approvals/admin-courier-approvals.component').then((m) => m.AdminCourierApprovalsPageComponent) },
            { path: 'admin/aprovacoes/admins', canActivate: [adminGuard], loadComponent: () => import('./pages/admin-admin-approvals/admin-admin-approvals.component').then((m) => m.AdminAdminApprovalsPageComponent) },
            { path: 'admin/pedidos', canActivate: [adminGuard], loadComponent: () => import('./pages/admin-orders/admin-orders.component').then((m) => m.AdminOrdersPageComponent) },
            { path: 'admin/financeiro', canActivate: [adminGuard], loadComponent: () => import('./pages/admin-financial/admin-financial.component').then((m) => m.AdminFinancialPageComponent) },
            { path: 'admin/auditoria', canActivate: [adminGuard], loadComponent: () => import('./pages/admin-audit/admin-audit.component').then((m) => m.AdminAuditPageComponent) },
            { path: 'admin/logs', canActivate: [adminGuard], loadComponent: () => import('./pages/admin-logs/admin-logs.component').then((m) => m.AdminLogsPageComponent) },
            { path: 'admin/configuracoes', canActivate: [adminGuard], loadComponent: () => import('./pages/admin-settings/admin-settings.component').then((m) => m.AdminSettingsPageComponent) },
            { path: 'contato', loadComponent: () => import('./pages/contact/contact.component').then((m) => m.ContactPageComponent) },
            { path: 'sobre', loadComponent: () => import('./pages/about/about.component').then((m) => m.AboutPageComponent) },
            { path: 'termos', loadComponent: () => import('./pages/terms/terms.component').then((m) => m.TermsPageComponent) },
            { path: 'privacidade', loadComponent: () => import('./pages/privacy/privacy.component').then((m) => m.PrivacyPageComponent) }
        ]
    },
    { path: '**', redirectTo: '' }
];
//# sourceMappingURL=app.routes.js.map