{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-test",
    "version": "3.4.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.4.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "3.4.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test-autoconfigure",
          "version": {
            "requires": "3.4.6"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "net.minidev",
          "module": "json-smart",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.26.3"
          }
        },
        {
          "group": "org.awaitility",
          "module": "awaitility",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "org.hamcrest",
          "module": "hamcrest",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.11.4"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "5.14.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.14.2"
          }
        },
        {
          "group": "org.skyscreamer",
          "module": "jsonassert",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "6.2.7"
          }
        },
        {
          "group": "org.xmlunit",
          "module": "xmlunit-core",
          "version": {
            "requires": "2.10.1"
          },
          "excludes": [
            {
              "group": "javax.xml.bind",
              "module": "jaxb-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-test-3.4.6.jar",
          "url": "spring-boot-starter-test-3.4.6.jar",
          "size": 4792,
          "sha512": "6907c02478d98462e49cbbec912a2be7ddc1291c2d79d415a4433b1104c59f76a154b8ebe2825436222e676ef786c626186b6c8f3aec510a96ffc673aa5fcbaa",
          "sha256": "571fe7b0c40b6c4070be7ae4ae180e7f02bfef829056fee94dc9b7e705e768f7",
          "sha1": "e3cbb62d86fb6e0a4a3c26f775288d299178217a",
          "md5": "0650c22674ab2b828fa8dae1a810d512"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.4.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "3.4.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test-autoconfigure",
          "version": {
            "requires": "3.4.6"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "net.minidev",
          "module": "json-smart",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.26.3"
          }
        },
        {
          "group": "org.awaitility",
          "module": "awaitility",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "org.hamcrest",
          "module": "hamcrest",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.11.4"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "5.14.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.14.2"
          }
        },
        {
          "group": "org.skyscreamer",
          "module": "jsonassert",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "6.2.7"
          }
        },
        {
          "group": "org.xmlunit",
          "module": "xmlunit-core",
          "version": {
            "requires": "2.10.1"
          },
          "excludes": [
            {
              "group": "javax.xml.bind",
              "module": "jaxb-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-test-3.4.6.jar",
          "url": "spring-boot-starter-test-3.4.6.jar",
          "size": 4792,
          "sha512": "6907c02478d98462e49cbbec912a2be7ddc1291c2d79d415a4433b1104c59f76a154b8ebe2825436222e676ef786c626186b6c8f3aec510a96ffc673aa5fcbaa",
          "sha256": "571fe7b0c40b6c4070be7ae4ae180e7f02bfef829056fee94dc9b7e705e768f7",
          "sha1": "e3cbb62d86fb6e0a4a3c26f775288d299178217a",
          "md5": "0650c22674ab2b828fa8dae1a810d512"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-test-3.4.6-javadoc.jar",
          "url": "spring-boot-starter-test-3.4.6-javadoc.jar",
          "size": 4792,
          "sha512": "9fb9eaedff19c93ca960c01eb2dcec25c8b64f49c53336fab3c33553283b6e668a60fa2a3920c0ce8e9b371176efa7e6b322912054786ef723660ee771b2501d",
          "sha256": "47a63ef53915294a5885b7d15e0b46b4f09794d3b833ef4b3ff707fbcd142547",
          "sha1": "b8fa353d0172e19211e43e6fab3d577c08fcc245",
          "md5": "9a7e94308110b4ef478feda840c19ba7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-test-3.4.6-sources.jar",
          "url": "spring-boot-starter-test-3.4.6-sources.jar",
          "size": 4792,
          "sha512": "9fb9eaedff19c93ca960c01eb2dcec25c8b64f49c53336fab3c33553283b6e668a60fa2a3920c0ce8e9b371176efa7e6b322912054786ef723660ee771b2501d",
          "sha256": "47a63ef53915294a5885b7d15e0b46b4f09794d3b833ef4b3ff707fbcd142547",
          "sha1": "b8fa353d0172e19211e43e6fab3d577c08fcc245",
          "md5": "9a7e94308110b4ef478feda840c19ba7"
        }
      ]
    }
  ]
}
