{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-cache",
    "version": "3.4.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.4.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context-support",
          "version": {
            "requires": "6.2.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-cache-3.4.6.jar",
          "url": "spring-boot-starter-cache-3.4.6.jar",
          "size": 4762,
          "sha512": "b7f1c5a442dedfb5242276f1c271c7adf3547516a761cdbbb53ace6df684a577755a462fef320ad5c62c921ed3e74f62ab9a99433eaa356dd387f129285c4cc0",
          "sha256": "4731e20789068441eac3014efdbbe6916eb8503603eedf094c129f5557b88f96",
          "sha1": "7e9af91b99044646dc1855b7445d6077db91b064",
          "md5": "376a9349c18fe3b19b0bbf2b267da434"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.4.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context-support",
          "version": {
            "requires": "6.2.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-cache-3.4.6.jar",
          "url": "spring-boot-starter-cache-3.4.6.jar",
          "size": 4762,
          "sha512": "b7f1c5a442dedfb5242276f1c271c7adf3547516a761cdbbb53ace6df684a577755a462fef320ad5c62c921ed3e74f62ab9a99433eaa356dd387f129285c4cc0",
          "sha256": "4731e20789068441eac3014efdbbe6916eb8503603eedf094c129f5557b88f96",
          "sha1": "7e9af91b99044646dc1855b7445d6077db91b064",
          "md5": "376a9349c18fe3b19b0bbf2b267da434"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-cache-3.4.6-javadoc.jar",
          "url": "spring-boot-starter-cache-3.4.6-javadoc.jar",
          "size": 4762,
          "sha512": "b7f1c5a442dedfb5242276f1c271c7adf3547516a761cdbbb53ace6df684a577755a462fef320ad5c62c921ed3e74f62ab9a99433eaa356dd387f129285c4cc0",
          "sha256": "4731e20789068441eac3014efdbbe6916eb8503603eedf094c129f5557b88f96",
          "sha1": "7e9af91b99044646dc1855b7445d6077db91b064",
          "md5": "376a9349c18fe3b19b0bbf2b267da434"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-cache-3.4.6-sources.jar",
          "url": "spring-boot-starter-cache-3.4.6-sources.jar",
          "size": 4762,
          "sha512": "b7f1c5a442dedfb5242276f1c271c7adf3547516a761cdbbb53ace6df684a577755a462fef320ad5c62c921ed3e74f62ab9a99433eaa356dd387f129285c4cc0",
          "sha256": "4731e20789068441eac3014efdbbe6916eb8503603eedf094c129f5557b88f96",
          "sha1": "7e9af91b99044646dc1855b7445d6077db91b064",
          "md5": "376a9349c18fe3b19b0bbf2b267da434"
        }
      ]
    }
  ]
}
